name: stess_mange
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_database: ^10.0.0
  provider: ^6.1.0
  fl_chart: ^0.63.0
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.0
  intl: ^0.18.0
  flutter_neumorphic: ^3.2.0
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/meditation.mp3
    - assets/images/Meditation.jpg
    - assets/videos/gentle_stretches.mp4
